---

- name: Disable systemd-resolv.service
  when: disable_resolvd | lower == 'true'
  block:
     - name: Disable systemd-resolved.service
       service: name=systemd-resolved.service state=stopped enabled=no

     - name: Check /etc/resolv.conf
       stat: path=/etc/resolv.conf
       register: resolv_result

     - name: Delete symlink /etc/resolv.conf
       when: resolv_result.stat.islnk | lower == 'true'
       file: state=absent path=/etc/resolv.conf

     - name: Set dns to none in Network Manager
       when: configure_nm | lower == 'true'
       ini_file:
          path: /etc/NetworkManager/conf.d/disableresolv.conf
          section: main
          option: dns
          value: none

- name: Set localhost as DNS service
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver"
    line: "nameserver 127.0.0.1"
    create: yes

- name: Main configuration
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.d/main
  notify: restart dnsmasq

- name: Forwarding zones configuration
  template: src=dnsmasq.zone.conf.j2 dest=/etc/dnsmasq.d/{{ item.name }}
  with_items: "{{ dnsmasq_forwarding_zones }}"
  notify: restart dnsmasq

- name: Consul monitoring
  when:
    - configure_consul | lower == 'true'
  block:
      - name: Create consul dnsmasq service
        template: src=service.consul.json.j2 dest={{ dnsmasq_consul_services_path }}/{{ item.service.name }}.json
        with_items: "{{ dnsmasq_consul }}"
        notify: reload consul

      - name: Create consul DNS queries service
        template: src=service.consul.json.j2 dest={{ dnsmasq_consul_services_path }}/{{ item.service.name }}.json
        notify: reload consul
