---
# handlers file for ansible-dnsmasq

- name: restart dnsmasq
  service: name=dnsmasq state=restarted enabled=yes

- name: reload systemd
  systemd: daemon_reload=yes

- name: reload consul
  service: name=consul state=reloaded
